# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  manage.matgargano.com:
    site_hosts:
      - canonical: manage.matgargano.com
      - canonical: multisite.matgargano.com

    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:matgargano/multisite.git
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: master
    multisite:
      enabled: true
      subdomains: true
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
    env:
      domain_current_site: manage.matgargano.com
